# Generated by Django 5.1.5 on 2025-03-22 05:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("gipl_app", "0002_remove_product_availability_remove_product_price_and_more"),
    ]

    operations = [
        migrations.DeleteModel(
            name="QuoteRequest",
        ),
    ]
