# Generated by Django 5.1.7 on 2025-03-22 13:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("gipl_app", "0003_delete_quoterequest"),
    ]

    operations = [
        migrations.CreateModel(
            name="HeroSlide",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("heading", models.CharField(max_length=150)),
                ("subheading", models.TextField()),
                ("cta_text", models.CharField(max_length=50)),
                ("cta_link", models.URLField()),
                ("image", models.ImageField(upload_to="hero/")),
            ],
        ),
    ]
