# Generated by Django 5.1.7 on 2025-03-22 14:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("gipl_app", "0004_heroslide"),
    ]

    operations = [
        migrations.CreateModel(
            name="HeroImage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("image", models.ImageField(upload_to="hero/")),
                ("alt_text", models.CharField(default="Hero image", max_length=150)),
            ],
        ),
        migrations.DeleteModel(
            name="HeroSlide",
        ),
    ]
