# Generated by Django 5.1.7 on 2025-03-22 15:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("gipl_app", "0005_heroimage_delete_heroslide"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="heroimage",
            name="image",
        ),
        migrations.AddField(
            model_name="heroimage",
            name="desktop_image",
            field=models.ImageField(default=1, upload_to="hero/desktop/"),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="heroimage",
            name="mobile_image",
            field=models.ImageField(default=1, upload_to="hero/mobile/"),
            preserve_default=False,
        ),
    ]
