# Generated by Django 5.1.7 on 2025-03-25 20:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("gipl_app", "0008_productcategory_image"),
    ]

    operations = [
        migrations.AddField(
            model_name="productcategory",
            name="description",
            field=models.TextField(blank=True, null=True),
        ),
    ]
