# Generated by Django 5.1.7 on 2025-03-27 18:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("gipl_app", "0009_productcategory_description"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="testimonial",
            name="created_at",
        ),
        migrations.AlterField(
            model_name="testimonial",
            name="company",
            field=models.CharField(max_length=150),
        ),
        migrations.AlterField(
            model_name="testimonial",
            name="image",
            field=models.ImageField(upload_to="testimonials/"),
        ),
        migrations.AlterField(
            model_name="testimonial",
            name="name",
            field=models.CharField(max_length=100),
        ),
    ]
