# Generated by Django 5.1.7 on 2025-03-27 19:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("gipl_app", "0010_remove_testimonial_created_at_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="inquiry",
            name="country_code",
            field=models.CharField(default=1, max_length=10),
            preserve_default=False,
        ),
    ]
