# Generated by Django 5.2.8 on 2026-03-14 13:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("gipl_app", "0012_product_attributes_product_exported_to_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="productcategory",
            name="subdomain_prefix",
            field=models.CharField(
                blank=True,
                help_text="Type the subdomain here. e.g., 'stationary' for stationary.gitanshuimpex.com",
                max_length=50,
                null=True,
                unique=True,
            ),
        ),
    ]
