# Generated by Django 4.2.1 on 2026-03-15 07:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gipl_app', '0013_productcategory_subdomain_prefix'),
    ]

    operations = [
        migrations.CreateModel(
            name='Subdomain',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='e.g., Industrial Tools', max_length=100)),
                ('prefix', models.CharField(help_text="e.g., 'industrial' for industrial.gitanshuimpex.com", max_length=50, unique=True)),
                ('is_active', models.BooleanField(default=True)),
                ('hero_subtitle', models.TextField(blank=True, null=True)),
                ('meta_title', models.CharField(blank=True, max_length=200, null=True)),
                ('meta_description', models.TextField(blank=True, null=True)),
                ('hero_title', models.CharField(blank=True, max_length=200, null=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='productcategory',
            name='subdomain_prefix',
        ),
        migrations.AddField(
            model_name='productcategory',
            name='subdomain',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='categories', to='gipl_app.subdomain'),
        ),
    ]
