# Generated by Django 4.2.1 on 2026-03-15 07:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gipl_app', '0014_subdomain_remove_productcategory_subdomain_prefix_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='inquiry',
            options={'verbose_name_plural': 'Inquiries'},
        ),
    ]
