# Generated by Django 4.2.1 on 2026-03-15 07:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gipl_app', '0015_alter_inquiry_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='inquiry',
            name='source_subdomain',
            field=models.CharField(blank=True, help_text='The subdomain where the lead originated', max_length=100, null=True),
        ),
    ]
